apiVersion: apps/v1
kind: Deployment
metadata:
  name: fm-webapp-dep
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      name: fm-eval-rr
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: fm-eval-rr
    spec:
      containers:
      - image: ramkamalrao/fm-tech-eval
        name: fm-eval-rr
        ports:
        - containerPort: 80