apiVersion: v1
kind: Service
metadata:
  name: fm-webapp-ser
  namespace: default
spec:
  ports:
  - nodePort: 30090
    port: 80
    targetPort: 80 
    protocol: TCP
  selector:
    name: fm-eval-rr
  type: NodePort